- name: A sample playbook header
  hosts: localhost
  user: ubuntu

  tasks:
  - name: 1. Pull node dockerfile from dockerhub
    shell:
      cmd: docker pull alexgoffo200/coursework2:latest

  - name: 2. Create a kubectl deployment with a proxy
    shell:
      cmd: kubectl create deployment coursework2-deployment --image=alexgoffo200/coursework2

  - name: 3. Creating a new service for the application
    shell:
      cmd: kubectl expose deployment/coursework2-deployment --type="NodePort" --port 8080 --name node-port-service

  - name: 4. Scaling deployment to allow for rolling updates to be implemented.
    shell:
      cmd: kubectl scale deployments/coursework2-deployment --replicas=4




