- name: A playbook to install Kubectl and Minikube on a VM
  hosts: localhost
  user: ubuntu
  become: yes

  tasks:
  - name: 1. Update Package Manager
    apt:
      update_cache: yes

  - name: 2. Install dependency package
    apt:
      update_cache: yes
      name: apt-transport-https

  - name: 3. Get APT Key
    shell:
      cmd: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

  - name: 4. Echo
    shell:
      cmd: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list

  - name: 5. Get Update
    apt:
      update_cache: yes

  - name: 6. Install Kubectl
    apt:
      update_cache: yes 
      name: kubectl

  - name: 7. Downloading minikube
    shell:
      cmd: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

  - name: Copy a file in Ansible
    copy:
      src: /home/ubuntu/minikube
      dest: /usr/local/bin/minikube

  - name: 8. Change Minikube permissions
    file:
      path: /usr/local/bin/minikube
      owner: ubuntu
      group: ubuntu
      mode: '+x'

  - name: 9. Minikube start
    shell:
      cmd: minikube start --driver=docker
    become: false
